export const PRODUCT_LIST = 'PRODUCT_LIST';
export const SET_PRODUCT_LIST = 'SET_PRODUCT_LIST';
export const GET_PRODUCT_DETAILS_REQUEST = 'GET_PRODUCT_DETAILS_REQUEST';
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS';
export const GET_PRODUCT_DETAILS_FAIL = 'GET_PRODUCT_DETAILS_FAIL';
export const SET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const SET_SEARCH_PRODUCTS = 'SET_SEARCH_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_TO_CART = 'REMOVE_TO_CART';
export const SET_ADD_TO_CART = 'SET_ADD_TO_CART';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';
export const GET_SORT_PRODUCTS_REQUEST = 'GET_SORT_PRODUCTS_REQUEST';
export const GET_SORT_PRODUCTS_SUCCESS = 'GET_SORT_PRODUCTS_SUCCESS';
export const GET_FILTER_PRODUCTS_REQUEST = 'GET_FILTER_PRODUCTS_REQUEST';
export const GET_FILTER_PRODUCTS_SUCCESS = 'GET_FILTER_PRODUCTS_SUCCESS';

